import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import { componentTagger } from "lovable-tagger";
import viteImagemin from "@vheemstra/vite-plugin-imagemin";
import imageminWebp from "imagemin-webp";
import imageminMozjpeg from "imagemin-mozjpeg";
import imageminPngquant from "imagemin-pngquant";
import imageminSvgo from "imagemin-svgo";

// Sitemap is now generated by scripts/gen-sitemap.mjs (run after vite build)
// so it can include Supabase project slugs and per-route priorities.

export default defineConfig(({ mode }) => ({
  server: {
    host: "::",
    port: 8080,
    hmr: { overlay: false },
  },
  plugins: [
    react(),
    mode === "development" && componentTagger(),
    // ── Image optimisation: auto-convert to WebP on every build ──────────
    // Only run during production builds to keep dev server fast
    mode === "production" && viteImagemin({
      plugins: {
        jpg: imageminMozjpeg({ quality: 82 }),
        png: imageminPngquant({ quality: [0.7, 0.9], speed: 1 }),
        svg: imageminSvgo({ plugins: [{ name: "preset-default" }] }),
      },
      makeWebp: {
        plugins: {
          jpg: imageminWebp({ quality: 82 }),
          png: imageminWebp({ quality: 82 }),
        },
        skipIfLargerThan: "optimized",
      },
    }),
  ].filter(Boolean),
  resolve: {
    alias: { "@": path.resolve(__dirname, "./src") },
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          "vendor-react":    ["react", "react-dom", "react-router-dom"],
          "vendor-ui":       ["@radix-ui/react-dialog", "@radix-ui/react-dropdown-menu", "@radix-ui/react-tooltip"],
          "vendor-gsap":     ["gsap"],
          "vendor-md":       ["react-markdown", "remark-gfm", "rehype-raw", "gray-matter"],
          "vendor-embla":    ["embla-carousel-react"],
          "vendor-query":    ["@tanstack/react-query"],
          "vendor-supabase": ["@supabase/supabase-js"],
        },
      },
    },
    cssMinify: true,
    chunkSizeWarningLimit: 600,
  },
}));
